name = "cloudflare-docker-proxy-auto"
compatibility_date = "2026-01-01"
main = "dist/main.js" 

# 全局默认变量
[vars]
CUSTOM_DOMAIN = "tyjmirror.xyz"
MODE = "proxy"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy-auto"
# 这里的变量必须包含所有运行所需的 Key
vars = { CUSTOM_DOMAIN = "tyjmirror.xyz", MODE = "proxy", TARGET_UPSTREAM = "https://registry-1.docker.io" }
routes = [
  { pattern = "docker.tyjmirror.xyz", custom_domain = true },
  { pattern = "quay.tyjmirror.xyz", custom_domain = true },
  { pattern = "gcr.tyjmirror.xyz", custom_domain = true },
  { pattern = "k8s-gcr.tyjmirror.xyz", custom_domain = true },
  { pattern = "k8s.tyjmirror.xyz", custom_domain = true },
  { pattern = "ghcr.tyjmirror.xyz", custom_domain = true }
]

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"
